name: auto_js2abap
on: 
  push:
    branches: 
      - "main"
  workflow_dispatch:

jobs:
  auto_js2abap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: run transformation
        run: |
          cd app
          npm run transform
          cd .. 
          npm ci
          npm run auto_abaplint

      - name: Open PR
        uses: peter-evans/create-pull-request@v4
        with:
          title: auto-js2abap
          branch: auto-js2abap
